### PR TITLE
Add another source for groups of filters

### PR DESCRIPTION
**Pull request by dafatov**
I dug into the html of some search results and found that some have a list of filters hidden under popup. Actually added an additional path and an empty array, if not found at all

### CODE REVIEW

**Comment by AaronMeyers** [comment]
@dafatov thanks for this fix. i made this change to the file inside my node_modules folder weeks ago.

i’m surprised this hasn’t been approved. ytsr is basically unusable without it.

**Comment by Dajust** [comment]
This seems to be a good fix for this issue, thanks! @TimeForANinja mind taking a look?

**Comment by LaurenceMillward** [comment]
@TimeForANinja this is causing issues in a few projects, merging would be appreciated if all is ok.

**Comment by TimeForANinja** [comment]
thanks for the pr @dafatov 
bot should merge and push it automatically 😉

**Pull request merged**
