### PR TITLE
Fix for videos with no description / Temporary fix for non-existent published dates

### PR DESCRIPTION
**Pull request by Synkky**
Some videos are lacking the information regarding the published dates. Not sure why exactly that's happening but this should at least prevent errors from occurring.

This should solve FreeTubeApp/FreeTube#718

### CODE REVIEW

**Comment by Synkky** [comment]
I've also noticed that #76 already covers the description change, the difference is that I return an empty string while they return null. Tell me if you prefer their solution and I'll remove that commit.

Also, #76 solution for the `uploaded_at` field won't work, because in line 48 of the `util_v2.js` file, it's testing `item[type].publishedTimeText.simpleText`, however `item[type].publishedTimeText` might not actually exist, resulting in an error of attempting to access a field in an undefined object.

**Comment by userlip** [comment]
Am on my phone right now, but it actually works :) the item in the description was returned as is with the changes I made.

**Comment by Synkky** [comment]
@userlip 
Yeah, there's nothing wrong with the description solution, I just honestly don't know what's better: `null` or `''`

**Comment by userlip** [comment]
I was talking about the uploded_at solution :)

**Comment by Synkky** [comment]
@userlip 
Clone your repo, switched to wip branch, results:
Screenshot_2

**Comment by userlip** [comment]
My bad! Seems like I was wrong about getting back all different kinds of search results. Tried it with your search term and the error did come up on my end too.

Fixed it now though :)

**Comment by Synkky** [comment]
Since mine is pretty much the same as #76, I'll close this PR.

**Pull request closed without merging**
