### PR TITLE
Using new YouTube search API

### LINKED ISSUE #71: Unexpected token < in JSON at position 0
Some searches are returning this error... probably something related to JSON.parse() function.

### PR DESCRIPTION
**Pull request by skick1234**
This is my temporary solution to fix #71 
I have not used `getFilters` and other options so I cannot upgrade `ytsr` to v2
I hope you have time to rewrite v2 soon

### CODE REVIEW

**Comment by Ragzouken** [comment]
seems not to correctly detect `live` e.g when searching `hello` i get this:
```
{
  type: 'video',
  live: false,
  title: 'Hello Halloween - A Special Hello Neighbor Event',
  thumbnail: 'https://i.ytimg.com/vi/4SIC3FeKGX0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA6oxs-fSn8iK7WCDNZDJXpoKvFkQ',
  upcoming: 1603650600000,
  author: {
    name: 'tinyBuildGAMES',
    ref: 'https://www.youtube.com/user/tinyBuildGAMES',
    verified: true
  },
  description: 'We will be talking about Hello Neighbor 2 & Secret Neighbor Halloween events, and revealing something something completely ...',
  views: null,
  duration: null,
  uploaded_at: null
}
```

however despite that i was able to filter based on the lack of a duration and use this as a drop-in replacement for the current npm package, so thank you!

**Comment by skick1234** [comment]
This is scheduled live, you can see `upcoming` value.

**Comment by TimeForANinja** [comment]
looks to me like you're using youtubes official api which requires an api key
this is not the scope of this project - which is basically a web-scraper 🤔

**Comment by skick1234** [comment]
> looks to me like you're using youtubes official api which requires an api key
> this is not the scope of this project - which is basically a web-scraper 🤔 

But with new youtube search, I cannot get continuation results with get request. And if the first content is an ads (example keywords: toy, frozen, car,...), I cannot get any results.

**Comment by TimeForANinja** [comment]
🤔 might not like switching to api-tokens but don't see how else i would fetch continuation

**Pull request closed without merging**
