### PR TITLE
fix: address reelPlayerHeaderRenderer when undefined

### LINKED ISSUE #188: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
With the latest update I am getting this error.

```
TypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
    at parseShort (/Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:357:67)
    at parseItem (/Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:28:14)
    at /Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:411:30
    at Array.map (<anonymous>)
    at parseShelf (/Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:411:21)
    at parseItem (/Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/parseItem.js:113:46)
    at /Users/za/Documents/projects/db-bot/node_modules/ytsr/lib/main.js:53:34
    at Array.map (<anonymous>)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
pls post the the files in local_path/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: darwin-arm64, node.js: v18.15.0, ytsr: 3.8.1
********************************************************************************************************************************************************************************************************\
```

### LINKED ISSUE #191: bunch of errors in console even though everything is working
i get several errors like this, can't figure out when exactly
ypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
    at parseShort (/home/arina/node_modules/ytsr/lib/parseItem.js:357:67)
    at parseItem (/home/arina/node_modules/ytsr/lib/parseItem.js:28:14)
    at /home/arina/node_modules/ytsr/lib/parseItem.js:411:30
    at Array.map (<anonymous>)
    at parseShelf (/home/arina/node_modules/ytsr/lib/parseItem.js:411:21)
    at parseItem (/home/arina/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/home/arina/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/arina/node_modules/ytsr/lib/parseItem.js:113:46)
    at /home/arina/node_modules/ytsr/lib/main.js:53:34
    at Array.map (<anonymous>)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
pls post the the files in /home/arina/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v19.8.1, ytsr: 3.8.1

### PR DESCRIPTION
**Pull request by reply2za**
Node-ytsr team.
This update fixes #188.

I noticed that the local tests were also throwing the same error. That is no longer the case after this fix.

closes #188 
closes #191

### CODE REVIEW

**Comment by Reply2Zain** [comment]
Didn't notice the lint issue prior to pushing. I updated the code to prevent the use of the ternary operator "?", which causes the lint error.

**Comment by TimeForANinja** [comment]
i have to trigger the ci/cd manually for first-time contributors

anyway, do you still have the dump-file?
i don't think we should even enter the parseShort function if `obj` is not a short
and if it is a short there informations have to be at some place, don't they?

**Comment by Reply2Zain** [comment]
Sure, these are in the dump folder. I get this error with every query.

[3tb3rfn1uk-1680185805611.txt](https://github.com/TimeForANinja/node-ytsr/files/11112574/3tb3rfn1uk-1680185805611.txt)

[5eo04z4td4-1680185805608.txt](https://github.com/TimeForANinja/node-ytsr/files/11112575/5eo04z4td4-1680185805608.txt)

**Comment by Reply2Zain** [comment]
> anyway, do you still have the dump-file? i don't think we should even enter the parseShort function if `obj` is not a short and if it is a short there informations have to be at some place, don't they?

I spent quite some time trying to figure that out. These items are shorts but they are missing some objects in the payload. It appears that youtube has updated the provided data for shorts on a specific page or entry-point. You can see this for yourself with the dump files or by running your unit tests on the original branch.

The main difference is that there is no channel information, but all other information can be retrieved (although not always from the same object). I made an update to `parseShort` so that if we were to receive limited metadata on the short, instead of returning a undefined reference error, we can still return the short's parsed data... just without the channel info.

I also added a new dump file to the tests that covers the type of response I am seeing in my latest dump files. I also updated the expected parsed result. The new addition to the test suite runs and passes with the latest commit.

**Pull request merged**
