### PR TITLE
fix(ads): Add reelPlayerHeaderRenderer

### LINKED ISSUE #171: adSlotRenderer is not known
Evening! I'm using npm package `discord-music-player` and I get the following issue **only when loading a playlist into the system**.

```
Error: type adSlotRenderer is not known
    at parseItem (A:\GitHub\Framework-v14\node_modules\ytsr\lib\parseItem.js:81:13)
    at catchAndLogFunc (A:\GitHub\Framework-v14\node_modules\ytsr\lib\parseItem.js:88:12)
    at module.exports (A:\GitHub\Framework-v14\node_modules\ytsr\lib\parseItem.js:111:46)
    at A:\GitHub\Framework-v14\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (A:\GitHub\Framework-v14\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.search (A:\GitHub\Framework-v14\node_modules\discord-music-player\dist\utils\Utils.js:82:26)
    at async A:\GitHub\Framework-v14\node_modules\discord-music-player\dist\utils\Utils.js:242:32

/********************************************************************************************************************************************************************************************************
failed at func parseItem: type adSlotRenderer is not known
pls post the the files in A:\GitHub\Framework-v14\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.17.0, ytsr: 3.8.0
********************************************************************************************************************************************************************************************************\
```

Paste available at: https://paste.jx.wtf/iroqarivin.md

Files: https://paste.jx.wtf/wopugejodo.json // https://paste.jx.wtf/rekenozeya.json
(There's more but they're virtually the same)

Any help is appreciated, cheers folks!

### LINKED ISSUE #174: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
Error while parsing Shorts.

### Code:
ytsr("test", {
      limit: 20
    })

### Log:
TypeError: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
    at parseShort (C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:355:67)
    at parseItem (C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:28:14)
    at C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:409:30
    at Array.map (<anonymous>)
    at parseShelf (C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:409:21)
    at parseItem (C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:32:14)
    at catchAndLogFunc (C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:88:12)
    at module.exports (C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\parseItem.js:111:46)
    at C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')
pls post the the files in C:\Users\alexs\development\discord-bot-node\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.13.0, ytsr: 3.8.0
********************************************************************************************************************************************************************************************************\

### Relevant ytsr code:
const parseShort = obj => {
  const playerHeader = obj.navigationEndpoint.reelWatchEndpoint.overlay
    .reelPlayerOverlayRenderer.reelPlayerHeaderSupportedRenderers.reelPlayerHeaderRenderer;

### Dumps:
[w4v30m7nxg-1673000032404.txt](https://github.com/TimeForANinja/node-ytsr/files/10359436/w4v30m7nxg-1673000032404.txt)
[n6qohp7t1k-1673000874734.txt](https://github.com/TimeForANinja/node-ytsr/files/10359437/n6qohp7t1k-1673000874734.txt)

### PR DESCRIPTION
**Pull request by InfinityJxck**
Add `reelPlayerHeaderRenderer` to the Skip ads case block.
Must be a new thing YouTube added that's not yet handled.

closes #174 
closes #171

### CODE REVIEW

**Comment by watzon** [comment]
This looks like it would close #174. Please merge

**Comment by cyph84** [comment]
I think you merged in some merge conflicts in parseItem.js

**Review by Calemy — CHANGES_REQUESTED** [review]
you might wanna remove the git changes from the code

**Review by TimeForANinja — APPROVED** [review]

**Comment by TimeForANinja** [comment]
wondering why the actions don't run 🤔

**Comment by TimeForANinja** [comment]
thanks for the PR - hope the CI/CD deploys it in time 👍

**Pull request merged**
